# 리스트에서 텐서로

In [1]:
import torch

- List

In [2]:
a = [1.0 , 2.0, 3.0]

In [3]:
print(a[0])
print(a)

1.0
[1.0, 2.0, 3.0]


- Tensor

In [4]:
b = torch.ones(3) # 크기가 3인 1차원 텐서를 만들고 값을 1로 채우기

print(b[0])
print(b)

tensor(1.)
tensor([1., 1., 1.])


## Tensor 생성 방법 - 1

In [7]:
points = torch.zeros(3)
points[0] = 1.
points[1] = 2.
points[2] = 3.

print(points)

tensor([1., 2., 3.])


In [11]:
points = torch.zeros(3,2)
print(points)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


## Tensor 생성 방법 - 2

In [10]:
points = torch.tensor([1.,2.,3.])
print(points)

tensor([1., 2., 3.])


In [13]:
points = torch.tensor([[4.,1.],[5.,3.],[2.,1.]])
print(points)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


# Tensor 인덱싱

In [14]:
print(points)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [17]:
print(f'poinsts[1:] : \n {points[1:]} \n')
print(f'points[1:, :] : \n {points[1:, :]} \n')
print(f'points[1:, 0] : \n{points[1:, 0]} \n')
print(f'points[None] : \n{points[None]} \n points[None] 의 shpae : {points[None].shape}')

poinsts[1:] : 
 tensor([[5., 3.],
        [2., 1.]]) 

points[1:, :] : 
 tensor([[5., 3.],
        [2., 1.]]) 

points[1:, 0] : 
tensor([5., 2.]) 

points[None] : 
tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]]) 
 points[None] 의 shpae : torch.Size([1, 3, 2])
