# 리스트에서 텐서로

In [1]:
import torch

- List

In [2]:
a = [1.0 , 2.0, 3.0]

In [3]:
print(a[0])
print(a)

1.0
[1.0, 2.0, 3.0]


- Tensor

In [4]:
b = torch.ones(3) # 크기가 3인 1차원 텐서를 만들고 값을 1로 채우기

print(b[0])
print(b)

tensor(1.)
tensor([1., 1., 1.])


## Tensor 생성 방법 - 1

In [7]:
points = torch.zeros(3)
points[0] = 1.
points[1] = 2.
points[2] = 3.

print(points)

tensor([1., 2., 3.])


In [11]:
points = torch.zeros(3,2)
print(points)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


## Tensor 생성 방법 - 2

In [10]:
points = torch.tensor([1.,2.,3.])
print(points)

tensor([1., 2., 3.])


In [13]:
points = torch.tensor([[4.,1.],[5.,3.],[2.,1.]])
print(points)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


# Tensor 인덱싱

In [14]:
print(points)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [17]:
print(f'poinsts[1:] : \n {points[1:]} \n')
print(f'points[1:, :] : \n {points[1:, :]} \n')
print(f'points[1:, 0] : \n{points[1:, 0]} \n')
print(f'points[None] : \n{points[None]} \n points[None] 의 shpae : {points[None].shape}')

poinsts[1:] : 
 tensor([[5., 3.],
        [2., 1.]]) 

points[1:, :] : 
 tensor([[5., 3.],
        [2., 1.]]) 

points[1:, 0] : 
tensor([5., 2.]) 

points[None] : 
tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]]) 
 points[None] 의 shpae : torch.Size([1, 3, 2])


# dtype 설정 및 확인 방법

In [18]:
# Dtype 설정
double_points = torch.ones(10,2 , dtype=torch.double)
short_points = torch.tensor([[1,2],[3,4]], dtype = torch.short)

In [19]:
print(f'double_points : {double_points}')
print(f'short_points : {short_points}')

double_points : tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
short_points : tensor([[1, 2],
        [3, 4]], dtype=torch.int16)


In [21]:
print(double_points.dtype)
print(short_points.dtype)

torch.float64
torch.int16


# dtype 변경 방법 

In [24]:
print(torch.zeros(10,2))
print(f'types : {torch.zeros(10,2).dtype}')

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
types : torch.float32


In [25]:
print(f'Change double type : \n {torch.zeros(10,2).double().dtype}')

Change double type : 
 torch.float64


In [27]:
print(f'Change short type : \n {torch.zeros(10,2).short().dtype}')

Change short type : 
 torch.int16


In [29]:
print(f'Change double type -v2 : \n {torch.zeros(10,2).to(torch.double).dtype}')

Change double type -v2 : 
 torch.float64


In [31]:
print(f'Change short type -v2 : \n {torch.zeros(10,2).to(torch.short).dtype}')

Change short type -v2 : 
 torch.int16


# 여러가지 타입일 경우

- 여러가지 타입을 가지고 있을 경우 텐서들을 합할때 자동으로 가장 큰 타입으로 바뀐다.

In [32]:
points_64 = torch.rand(5, dtype=torch.double) # 0과 1 사이 임의의 수로 초기화
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [33]:
print((points_64 * points_short).dtype)

torch.float64


# 여러가지 텐서 API 

In [34]:
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)

print(a.shape, a_t.shape)

torch.Size([3, 2]) torch.Size([2, 3])


In [35]:
a = torch.ones([3,2])
a_t = a.transpose(0,1)

print(a.shape, a_t.shape)

torch.Size([3, 2]) torch.Size([2, 3])


# 탠서를 GPU 로 옮기기

In [36]:
import torch

print(torch.backends.mps.is_available())

True


In [38]:
device = 'mps' if torch.backends.mps.is_available() else 'cpu'

points_gpu = torch.tensor([[4.,1.],[5.,3.],[2.,1.]], device=device)
print(points_gpu)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='mps:0')


In [39]:
points = torch.tensor([[4.,1.],[5.,3.],[2.,1.]])
print(points)

points_gpu = points.to(device)

print(points_gpu)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='mps:0')


# 넘파이 호환

In [41]:
points = torch.ones(3,4)
print(f'Tensor : {points}')
points_np = points.numpy()
print(f'Numpy : ')
print(points_np)
print(points_np.dtype)

Tensor : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Numpy : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float32


In [43]:
# numpy -> torch
points = torch.from_numpy(points_np)
print(points)
print(points.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


# 텐서의 직렬화

In [44]:
print(points)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


- points tensor를 'ourpoints.t' 로 직렬화 시킨다.

In [45]:
torch.save(points, './ourpoints.t')

In [47]:
# 다른 방법
with open('./ourpoints_discriptor.t', 'wb') as f:
    torch.save(points, f)

- 텐서 읽어오기

In [48]:
load_points = torch.load('./ourpoints.t')

In [49]:
print(load_points)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [51]:
# 다른 방법
with open('./ourpoints_discriptor.t', 'rb') as f:
    load_discriptor_load = torch.load(f)

print(load_discriptor_load)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


# h5py로 HDF5 병렬화 하기

In [52]:
import h5py

f = h5py.File('./ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data= points.numpy())
f.close()

In [53]:
f = h5py.File('./ourpoints.hdf5', 'r')
dset = f['coords']
print(dset)

<HDF5 dataset "coords": shape (3, 4), type "<f4">


In [55]:
last_points = dset[-2:]
print(last_points)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [56]:
last_pints = torch.from_numpy(dset[-2:])
print(last_points)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [57]:
f.close()

In [58]:
dset

<Closed HDF5 dataset>

In [59]:
dset[-2:]

ValueError: Dset_id is not a dataset id (dset_id is not a dataset ID)